var student_name="vinnykumar";
console.log("my name is:",student_name);
var java=98;
console.log("my java mark is:"+java);
var python=99;
console.log("my python mark is:"+python);
var oops=85;
console.log("my oops mark is:"+oops);
var example=[10,20,"html","css",12.4,"a"];
console.log(example);
console.log(example.length);
console.log(example[5]);
example.push("java");
console.log(example);
example.unshift("vinny");
console.log(example);
example.pop();
console.log(example);
example.shift();
console.log(example);